spring.application.name=currency-bot

bot.name=${BOT_NAME}
bot.token=${BOT_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost:5432/currencydb
spring.datasource.username=shop
spring.datasource.password=shop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
anthropic.api-key=${ANTHROPIC_API_KEY:stub}
newsapi.api-key=${NEWSAPI_API_KEY:stub}

bot.admin.chatId=${BOT_ADMIN:stub}