spring.application.name=currency-bot

bot.name=name21
bot.token=8064096026:AAH9StOjlLq3PSfEKdUQ2K0NUCa9RP3W6v8

spring.datasource.url=jdbc:postgresql://localhost:5432/currencydb
spring.datasource.username=shop
spring.datasource.password=shop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

bot.admin.chatId=0