spring.datasource.url=jdbc:postgresql://localhost:5432/botdb
spring.datasource.username=shop
spring.datasource.password=shop

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

telegram.bot.token=8612368376:AAGGz7V3v-Evlho_-s4EWD_DRgeINDgyhx8
telegram.bot.username=ToDoGooBot
server.port=8080